### ISSUE TITLE
Unified versioning of tools

### ISSUE THREAD

**Issue by aparcar** [BR903/ELFkickers#15]
Hi,

the source version and version stored in tools is different. Would it be possible to keep them in sync?

For example, `sstrip` would show version 2.1 even if the current code is 3.1.a:

https://github.com/BR903/ELFkickers/blob/dbeb4972ec3bddd1163608b7958e267cec594664/sstrip/sstrip.c#L33

**Comment by rsalvaterra** [comment]
Friendly ping. It would be nice to unify the versioning across all tools. Are there any plans for it?

**Comment by BR903** [comment]
Apologies for not responding sooner.

Is there an actual use case for unifying the version numbers? The various program in ELF kickers do not interoperate, nor are they particularly meant to be used together. (In fact, I doubt most of them are used at all, with sstrip being the exception. They are mainly intended to be instructive.)

**Comment by BR903** [comment]
> `sstrip` is heavily used inside of OpenWrt(.org).
> 
> Our build system uses a version variable to download code, currently
> 3.1a. Built packages result in names like `sstrip_3.1a-1.ipk`.
> Finding sstrip to print `2.1` is confusing, but doesn't actually
> break anything.

Thanks for the info. (I recently notice a dramatic increase in
downloads of ELF kickers, and wondered what was driving it.)

If sstrip is actually turning out to be useful, perhaps it would make
sense to pull it out and make it available in its own package, without
the baggage of the rest of ELF kickers.

b

**Comment by rsalvaterra** [comment]
> Thanks for the info. (I recently notice a dramatic increase in downloads of ELF kickers, and wondered what was driving it.)

Sorry about that. :) We had our own in-tree copy of a very old sstrip version I replaced it with the latest upstream.

>If sstrip is actually turning out to be useful, perhaps it would make sense to pull it out and make it available in its own package, without the baggage of the rest of ELF kickers.

Works for me. We actually carry a patch in order not to build anything other than sstrip, since elftoc doesn't compile against the musl libc.

**Comment by BR903** [comment]
> Sorry about that. :) We had our own in-tree copy of a very old
> sstrip version I replaced it with the latest upstream.

No, it's definitely better to be using the current version. The old
version in particular could misbehave in a cross-compiling situation.

> We actually carry a patch in order not to build elftoc, since it
> doesn't compile against the musl libc.

I didn't realize that. There's no reason why it shouldn't work.

Oh, it's almost certainly because the Makefile has hardcoded use of
gcc in building the helper program. I didn't think about the issue of
different compilers having different libc include files.

Thanks for letting me know -- that should be an easy fix. And I'll
think about making a standalone sstrip distro.

b

**Comment by BR903** [comment]
For now I'm closing this issue, since I feel that keep separate versioning for the utilities makes more sense for the package as a whole. Feel free to reopen if another rationale for changing this comes up.

(PS: I just released v3.2 of the package, and it should fix the issue with building elftoc.)

**Comment by rsalvaterra** [comment]
> (PS: I just released v3.2 of the package, and it should fix the issue with building elftoc.)

[It doesn't](https://pastebin.com/SJtz0xx2), unfortunately. However, it doesn't affect us (OpenWrt) directly.

**Comment by BR903** [comment]
Frustrating, but thanks for the info. I guess I would need to build openwrt myself in order to investigate this further.
