### ISSUE TITLE
rebind is not reading the hidden symbols

### ISSUE THREAD

**Issue by costashatz** [BR903/ELFkickers#17]
Thanks for the awesome small apps! :)

I've been trying to use `rebind` to unhide some symbols from a shared library (`so` file). When I do `nm libname.so` I get many symbols (including hidden ones). I do `rebind -v hidden -i libname.so symbol_name` and I always get `libname.so: nothing changed`. I was sure I was giving wrong symbol names, but I edited the code to print the name of the symbols it searches over ([here](https://github.com/BR903/ELFkickers/blob/master/rebind/rebind.c#L151)) and only the 'visible' symbols are printed.

I also tried to change the visibility of a visible symbol to hidden and although I got the verbose output that was saying the libname.so got changed, nothing was changed (verified by nm).

Is there something more that I need to take into account? The file is 64bit and sadly I cannot share it since it is proprietary. Any ideas? 

Actually, I just tried on a very simple lib that I created and the issue persists (I tried on the `.o` object created as well with no luck). Either I have not understood something well about the `rebind` utility or there is something that I am missing. Thanks in advance!

**Comment by BR903** [comment]
> Actually, I just tried on a very simple lib that I created and the
> issue persists (I tried on the `.o` object created as well with no
> luck). Either I have not understood something well about the
> `rebind` utility or there is something that I am missing. Thanks in
> advance!

Okay. So, I tried to reproduce your issue as follows:

    $ echo 'int foo = 42;' >libfoo.c
    $ gcc -shared -o libfoo.so libfoo.c
    $ cp libfoo.so libfoo-hidden.so
    $ ./rebind -v hidden -i libfoo-hidden.so foo
    libfoo-hidden.so: "foo" altered.
    libfoo-hidden.so: "foo" altered.
    $ cmp libfoo.so libfoo-hidden.so
    libfoo.so libfoo-hidden.so differ: byte 862, line 2

This indicates that the library was, in fact, modified. The change in
visibility can then be demonstrated with a test program:

    $ cat >bar.c
    #include <stdio.h>
    extern int foo;
    int main() { printf("foo = %d\n", foo); }
    $ gcc -Wl,-rpath=. bar.c libfoo.so
    $ ./a.out
    foo = 42
    $ gcc -Wl,-rpath=. bar.c libfoo-hidden.so
    $ ./a.out
    ./a.out: symbol lookup error: ./a.out: undefined symbol: foo

So, if you're seeing different behavior, we need to figure out how
your test case is different from mine. Please let me know!


It's possible that the confusion is just with the expected behavior? I
should perhaps note that when a symbol is properly hidden -- i.e. when
it's done by the linker, instead of by a postprocessing tool like
rebind -- then it doesn't even get added to the dynamic symbol table
in the first place:

    $ echo 'int __attribute((visibility("hidden"))) foo = 42;' >libfoo.c
    $ gcc -shared -o libfoo-reallyhidden.so libfoo.c
    $ diff <(nm libfoo-hidden.so) <(nm libfoo-reallyhidden.so)
    9c9
    < 0000000000004020 D foo
    ---
    > 0000000000004020 d foo

And that allows the symbol to be hidden not just at run-time but also
at link-time:

    $ gcc -Wl,-rpath=. bar.c libfoo-reallyhidden.so
    /usr/bin/ld: /tmp/cc9xBMGb.o: in function `main':
    bar.c:(.text+0xa): undefined reference to `foo'
    collect2: error: ld returned 1 exit status

It's probably worth moting that rebind (as you might have guessed from
the name) was originally written mainly to edit bindings. Editing
sybmol visibility was added later, and it is not quite as useful a
feature, due to the multiple ways that visibility is managed in ELF
files.

**Comment by costashatz** [comment]
> It's possible that the confusion is just with the expected behavior?

Reading your response I realized that I have misunderstood the tool. My use-case was to take a lib compiled with `__attribute((visibility("hidden")))` and unhide some of the symbols. :)

I figure this is not possible with this tool.

Thanks for the detailed response and all the nice tools. :)

**Comment by BR903** [comment]
> Reading your response I realized that I have misunderstood the tool.
> My use-case was to take a lib compiled with
> `__attribute((visibility("hidden")))` and unhide some of the
> symbols. :)
> 
> I figure this is not possible with this tool.

Ah, of course. I see now why it's not working for you.

No, unfortunately rebind isn't a particularly helpful, except maybe
for dealing with weak/global symbols. That is unfortunate.

In a future release, I will add a note to the README and/or man page
that makes this limitation clearer.

b

**Comment by costashatz** [comment]
Great! Thanks again! Cheers!
